package com.kingdee.eas.fi.cas;

import com.kingdee.bos.BOSException;
//import com.kingdee.bos.metadata.*;
import com.kingdee.bos.framework.*;
import com.kingdee.bos.util.*;
import com.kingdee.bos.Context;

import com.kingdee.eas.basedata.assistant.AccountBankCollection;
import java.lang.String;
import com.kingdee.bos.metadata.entity.EntityViewInfo;
import com.kingdee.eas.common.EASBizException;
import com.kingdee.bos.dao.IObjectPK;
import java.util.Map;
import com.kingdee.eas.fm.be.BankPayingBillInfo;
import com.kingdee.eas.fm.nt.ChequeInfo;
import com.kingdee.bos.metadata.entity.SelectorItemCollection;
import com.kingdee.eas.framework.CoreBaseCollection;
import com.kingdee.eas.basedata.assistant.AccountBankInfo;
import java.util.Set;
import com.kingdee.bos.util.*;
import com.kingdee.bos.dao.IObjectValue;
import com.kingdee.bos.BOSException;
import com.kingdee.bos.Context;
import com.kingdee.eas.framework.CoreBaseInfo;
import com.kingdee.bos.framework.*;
import java.util.ArrayList;
import com.kingdee.bos.util.BOSUuid;
import java.util.List;

public interface IPaymentBill extends IRecPayBill
{
    public PaymentBillInfo getPaymentBillInfo(IObjectPK pk) throws BOSException, EASBizException;
    public PaymentBillInfo getPaymentBillInfo(IObjectPK pk, SelectorItemCollection selector) throws BOSException, EASBizException;
    public PaymentBillInfo getPaymentBillInfo(String oql) throws BOSException, EASBizException;
    public PaymentBillCollection getPaymentBillCollection() throws BOSException;
    public PaymentBillCollection getPaymentBillCollection(EntityViewInfo view) throws BOSException;
    public PaymentBillCollection getPaymentBillCollection(String oql) throws BOSException;
    public int batchRemove(Set idSet) throws BOSException, EASBizException;
    public void audit(Set idSet) throws BOSException, EASBizException;
    public void audit4WF(IObjectPK pk) throws BOSException, EASBizException;
    public void audit4WF(IObjectPK pk, boolean isWfInVoked) throws BOSException, EASBizException;
    public void auditUnapprove(IObjectPK pk) throws BOSException, EASBizException;
    public boolean auditAndCommitSettle4WF(IObjectPK pk) throws BOSException, EASBizException;
    public void antiAudit(Set idSet) throws BOSException, EASBizException;
    public void antiAudit4WF(IObjectPK pk) throws BOSException, EASBizException;
    public void pay(Set idSet) throws BOSException, EASBizException;
    public void pay4WF(IObjectPK pk) throws BOSException, EASBizException;
    public void cancelPay(Set idSet) throws BOSException, EASBizException;
    public void cancelPay4WF(IObjectPK pk) throws BOSException, EASBizException;
    public void commitSettle(Set idSet) throws BOSException, EASBizException;
    public void cancelCommitSettle(Set idSet) throws BOSException, EASBizException;
    public void cancelCommitST4WF(IObjectPK pk) throws BOSException, EASBizException;
    public void commitSettle4WF(IObjectPK pk) throws BOSException, EASBizException;
    public void checkIsCanEditInit(String id) throws BOSException, EASBizException;
    public void writeOff(Set ids, ChequeInfo cheque) throws BOSException, EASBizException;
    public boolean audit4FDC(List idList) throws BOSException, EASBizException;
    public boolean antiAudit4FDC(List idList) throws BOSException, EASBizException;
    public void setAuditing4FDC(BOSUuid billId) throws BOSException, EASBizException;
    public void setAudited4FDC(BOSUuid billId) throws BOSException, EASBizException;
    public void antiAudit4FDC(BOSUuid billId) throws BOSException, EASBizException;
    public IObjectPK commitToBE(Set idSet) throws BOSException, EASBizException;
    public void setSubmit4FDC(BOSUuid billId) throws BOSException, EASBizException;
    public void pay(Set idSet, boolean commitToBe) throws BOSException, EASBizException;
    public void payForBook(Set idSet, boolean ifBookPayable) throws BOSException, EASBizException;
    public void payForBook(Set idSet, boolean ifBookPayable, boolean isInvokeWF) throws BOSException, EASBizException;
    public boolean isNeedCommitST(String id) throws BOSException, EASBizException;
    public int getBillStatus(String id) throws BOSException, EASBizException;
    public void submit(Set idSet) throws BOSException, EASBizException;
    public void cancelCommitToBE(String id) throws BOSException, EASBizException;
    public void approve(Set idSet) throws BOSException, EASBizException;
    public void untiApprove(Set idSet) throws BOSException, EASBizException;
    public void approve4WF(IObjectPK pk) throws BOSException, EASBizException;
    public void untiApprove4WF(IObjectPK pk) throws BOSException, EASBizException;
    public Map canVoucherParam(Map paramMap) throws BOSException, EASBizException;
    public Map saveBatch(List idList) throws BOSException, EASBizException;
    public void commitToBeAll(Set idSet, IObjectPK bankPayingbillId) throws BOSException, EASBizException;
    public void reserveForBE(Set idSet, String bankPayingbillId) throws BOSException, EASBizException;
    public void saveBatch(PaymentBillCollection paymentBillCollection) throws BOSException, EASBizException;
    public void submitBatch(PaymentBillCollection paymentBillCollection) throws BOSException, EASBizException;
    public void unitePay(Set idSet) throws BOSException, EASBizException;
    public void commitToBE4WF(IObjectPK pk) throws BOSException, EASBizException;
    public void autoCommitToBE4WF(IObjectPK pk) throws BOSException, EASBizException;
    public void autoPay4WF(IObjectPK pk) throws BOSException, EASBizException;
    public boolean canCommitToBE(IObjectPK pk) throws BOSException, EASBizException;
    public PaymentBillCollection recBeInfo(Set OBJPKColl, AccountBankCollection acctColl) throws BOSException, EASBizException;
    public Set dlFromSettle(IObjectValue info) throws BOSException, EASBizException;
    public Map dlFromStBatch(Set idSet) throws BOSException, EASBizException;
    public void chequeReimburse(String newChequeNumber, String paymentBillID) throws BOSException, EASBizException;
    public void editVouch(String billId) throws BOSException, EASBizException;
    public void getSuperUpdate(IObjectPK pk, IObjectValue value) throws BOSException, EASBizException;
    public List verifyBeInfo(Set idSet) throws BOSException, EASBizException;
    public Map paySilent(Set idSet) throws BOSException, EASBizException;
    public Map cancelPaySilent(Set idSet) throws BOSException, EASBizException;
    public boolean updatePrintCount(Map billMaps) throws BOSException, EASBizException;
    public void submitBill(IObjectPK pk) throws BOSException, EASBizException;
    public void cancelPayForCredit(Set idSet) throws BOSException, EASBizException;
    public void checkIsAdjustPeriod(List idList) throws BOSException, EASBizException;
    public IObjectPK commitToBENew(PaymentBillInfo paymentBill, boolean isNeedCommitToBank) throws BOSException, EASBizException;
    public ArrayList commitToBENewBatch(Set idSet) throws BOSException, EASBizException;
    public void reserveForBeException(String bankPayingbillId) throws BOSException, EASBizException;
    public void reserveForOtherException(BankPayingBillInfo info, String returnMsg) throws BOSException, EASBizException;
    public Map divisionPayBillType(Set idSet) throws BOSException, EASBizException;
    public void payPrivateToBE(List payList, AccountBankInfo accountBank) throws BOSException, EASBizException;
}